// Monaco Editor Themes
export const MONACO_THEMES = [
  'Active4D',
  'All Hallows Eve',
  'Amy',
  'Birds of Paradise',
  'Blackboard',
  'Brilliance Black',
  'Brilliance Dull',
  'Chrome DevTools',
  'Clouds',
  'Clouds Midnight',
  'Cobalt2',
  'Cobalt',
  'Dawn',
  'Dominion Day',
  'Dracula',
  'Dreamweaver',
  'Eiffel',
  'Espresso Libre',
  'GitHub Dark',
  'GitHub Light',
  'GitHub',
  'idleFingers',
  'IDLE',
  'iPlastic',
  'Katzenmilch',
  'krTheme',
  'Kuroir Theme',
  'LAZY',
  'MagicWB (Amiga)',
  'Merbivore',
  'Merbivore Soft',
  'monoindustrial',
  'Monokai Bright',
  'Monokai',
  'Night Owl',
  'Nord',
  'Oceanic Next',
  'Pastels on Dark',
  'Slush and Poppies',
  'Solarized-dark',
  'Solarized-light',
  'SpaceCadet',
  'Sunburst',
  'Textmate (Mac Classic)',
  'Tomorrow',
  'Tomorrow-Night-Blue',
  'Tomorrow-Night-Bright',
  'Tomorrow-Night-Eighties',
  'Tomorrow-Night',
  'Twilight',
  'Upstream Sunburst',
  'Vibrant Ink',
  'Xcode_default',
  'Zenburnesque'
] as const;

export type MonacoTheme = typeof MONACO_THEMES[number];